version: 0.1
plaintext:
  JAVA_HOME: "/opt/jdk1.8.0_192"
phases:
  install:
    run-as: root
    commands:
    - echo This is a installation
  pre_build:
    commands:
    - echo This is a pre build
  build:
    commands:
    - npm install
  post_build:
    commands:
    - echo Build must be completed
artifacts:
  files:
  - '**/*'
  discard-paths: no